#!/usr/bin/python

import argparse

import pkg_resources
from pyqtgraph.Qt import QtGui

from arpys.pit import mainwindow as mw

parser = argparse.ArgumentParser()
parser.add_argument('filename', nargs='?', default='')

args = parser.parse_args()

app = QtGui.QApplication([])

main_window = mw.MainWindow()
if args.filename :
    filename = args.filename
else :
    path = pkg_resources.resource_filename('arpys', 'pit/')
    filename = path + 'example_data.p'

main_window.data_handler.prepare_data(filename)
app.exec_()

