#!/usr/bin/python

import argparse

from pyqtgraph.Qt import QtGui

from arpys.pit import mainwindow as mw

parser = argparse.ArgumentParser()
parser.add_argument('filename')

args = parser.parse_args()

app = QtGui.QApplication([])

main_window = mw.MainWindow()
main_window.prepare_data(args.filename)
app.exec_()

